"""aded comments column

Revision ID: 4203b7c89ecb
Revises: 21744f7dbd4c
Create Date: 2022-05-17 10:04:43.451643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4203b7c89ecb'
down_revision = '21744f7dbd4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('blog', 'dislikes')
    op.drop_column('blog', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('blog', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('comments')
    # ### end Alembic commands ###
